### ISSUE TITLE
FCL0.5 FCLCollisionNode boost undefined

### ISSUE THREAD

**Issue by mryellow** [dartsim/dart#757]
FCL0.5 switches to using `std::shared_ptr` rather than `boost::shared_ptr`.

```
dart/dart/collision/fcl/FCLCollisionNode.cpp:354:5: error: ‘boost’ has not been declared
     boost::shared_ptr<fcl::CollisionGeometry> fclCollGeom
```

Switching to `std` compiles on my system with FCL 0.5 and Dart `release-5.1` branch. May need to detect the version and adjust the code depending on which is being used.

**Comment by jslee02** [comment]
Thanks for the report. It seems we need backporting #749 for DART 5.1.

**Comment by jslee02** [comment]
Could you check #749, and close this issue if it works for you?

**Comment by jslee02** [comment]
Please reopen if it's still the issue. Closing.
