### ISSUE TITLE
module 'dartpy.gui.osg' has no attribute 'GUIEventHandler

### ISSUE THREAD

**Issue by lisheng-k** [dartsim/dart#1602]
Hi,

I am using DARTpy, an error occurs when I run the examples in biped_stand. 
the detail is :
python3 main.py 
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    class InputHandler(dart.gui.osg.GUIEventHandler):
AttributeError: module 'dartpy.gui.osg' has no attribute 'GUIEventHandler'
the code is :  https://github.com/dartsim/dart/blob/main/python/examples/biped_stand/main.py
Does anyone know how to fix this?

thank you in advance.

**Comment by lisheng-k** [comment]
> Could you provide further info? How did you build or install dartpy? Which version/branch/tag? I was able to run the example with the current `main` branch with no errors.

thank you for the reply.
the dartpy was installed and build followed the instruction here: https://dartsim.github.io/install_dartpy_on_ubuntu.html, and I installed dartpy from source. 
the version is : HEAD, tag: v6.9.0

I also tried to install the dartpy with the latest source: 'commit 6338430d79f01ab71f181d82b7c8c590e0a8c2a0 (HEAD -> main, origin/main, origin/HEAD'
the source was then compiled and installed following the same instruction, but a new error come out: 'there is no module dartpy'.

I also tried uninstalled and reinstall the dartpy in the version HEAD, tag: v6.9.0, the error still exist.

It seems that only the code in version HEAD, tag: v6.9.0 can be compiled and installed.

thanks.

**Comment by jslee02** [comment]
`dartpy.gui.osg.GUIEventHandler` is not exposed to `dartpy` in 6.9.0, so `biped_stand` [isn't added in that version](https://github.com/dartsim/dart/tree/v6.9.0/python/examples).

Is there any reason you use 6.9.0? If not, please consider using the latest release, 6.11.1. I just confiremd that `biped_stand` works fine in 6.11.1. You could quickly test it using Docker if preferred: `docker pull dartsim/dart:6.11.1`

**Comment by lisheng-k** [comment]
![Screenshot from 2021-09-22 14-36-47](https://user-images.githubusercontent.com/34022140/134344737-1aa98e05-e947-4d86-aef6-cf966b9be321.png)

**Comment by jslee02** [comment]
Please run `install-dartpy` to install dartpy, which is changed since 6.10. The instruction in the website needs to be updated. [Here](https://github.com/dartsim/dart/blob/v6.11.1/Dockerfile#L53-L64) is an example procedure to install `dartpy`.

**Comment by lisheng-k** [comment]
thank you for your reply.

I tried to update the code to version 6.11.1, but I got another error, like "ModuleNotFoundError: No module named 'dartpy'" I installed the dartpy from source, with the same method, version 6.9.0 does not have the error "ModuleNotFoundError: No module named 'dartpy'".

Is there a way to check the reason for "ModuleNotFoundError: No module named 'dartpy'" ?

**Comment by lisheng-k** [comment]
now with version 6.9.0, the installation looks fine, 
![Screenshot from 2021-09-22 16-26-19](https://user-images.githubusercontent.com/34022140/134362702-b3620069-2a4f-43c8-b287-4f2b7d332893.png)
it's a bit wired on my system.

**Comment by lisheng-k** [comment]
> Please run `install-dartpy` to install dartpy, which is changed since 6.10. The instruction in the website needs to be updated (edit: now updated). [Here](https://github.com/dartsim/dart/blob/v6.11.1/Dockerfile#L53-L64) is an example procedure to install `dartpy`.

thank you. but I got a new problem now.
I uninstalled the dartpy, the update the source to 6.11.1, then ... 
![Screenshot from 2021-09-22 18-14-28](https://user-images.githubusercontent.com/34022140/134382057-c8a3c4fa-163c-4ed4-b947-ee66a75e9e87.png)

**Comment by jslee02** [comment]
Oh, I forgot that `-DDART_BUILD_DARTPY=ON` is still needed for DART < 6.12.

Please rerun cmake as: `cmake .. -DCMAKE_INSTALL_PREFIX=/usr/ -DCMAKE_BUILD_TYPE=Release -DDART_BUILD_DARTPY=ON`

**Comment by lisheng-k** [comment]
> Oh, I forgot that `-DDART_BUILD_DARTPY=ON` is still needed for DART < 6.12.
> 
> Please rerun cmake as: `cmake .. -DCMAKE_INSTALL_PREFIX=/usr/ -DCMAKE_BUILD_TYPE=Release -DDART_BUILD_DARTPY=ON`

ok ....
now 
does it matter ? "-- Could NOT find ODE (missing: ODE_DIR)" looks like the ODE_DIR is missing ...
![Screenshot from 2021-09-22 18-22-38](https://user-images.githubusercontent.com/34022140/134383233-ee8d6508-daee-486a-9bd3-d3e0bdfbb25f.png)

**Comment by jslee02** [comment]
> does it matter ? "-- Could NOT find ODE (missing: ODE_DIR)" looks like the ODE_DIR is missing ...

Please ignore the message, which is misleading. It's fixed in 6.12: https://github.com/dartsim/dart/issues/1599
