### PR TITLE
osg CMakeLists.txt: allow building without osg

### LINKED ISSUE #897: Compilation failure without osg on release-6.2 branch
I was recently testing a build of gazebo against a source build of the `release-6.2` branch of dart in our buildfarm, and dart failed to compile with complaints about osg. It works fine with `release-6.1`.

* [release-6.2 failure](https://build.osrfoundation.org/job/gazebo-any_dart4-devel-xenial-amd64-gpu-nvidia_docker/20/console)
* [release-6.1 success](https://build.osrfoundation.org/job/gazebo-any_dart4-devel-xenial-amd64-gpu-nvidia_docker/21/)

During configuration, it fails to find OpenSceneGraph:

~~~
CMake Warning at dart/gui/osg/CMakeLists.txt:30 (message):
  Could NOT find OpenSceneGraph nor OpenThreads -- we will skip dart-gui-osg

  If you believe you do have both OSG and OpenThreads installed, try setting
  OSG_DIR


~~~

but it still tries to compile osg support anyway:

~~~
Scanning dependencies of target dart-gui-osg
[ 86%] Building CXX object dart/gui/osg/CMakeFiles/dart-gui-osg.dir/ImGuiViewer.cpp.o
In file included from /var/lib/jenkins/workspace/gazebo-any_dart4-devel-xenial-amd64-gpu-nvidia_docker/dart/dart/gui/osg/ImGuiViewer.hpp:37:0,
                 from /var/lib/jenkins/workspace/gazebo-any_dart4-devel-xenial-amd64-gpu-nvidia_docker/dart/dart/gui/osg/ImGuiViewer.cpp:32:
/var/lib/jenkins/workspace/gazebo-any_dart4-devel-xenial-amd64-gpu-nvidia_docker/dart/dart/gui/osg/Viewer.hpp:39:28: fatal error: osgViewer/Viewer: No such file or directory
compilation terminated.
dart/gui/osg/CMakeFiles/dart-gui-osg.dir/build.make:62: recipe for target 'dart/gui/osg/CMakeFiles/dart-gui-osg.dir/ImGuiViewer.cpp.o' failed
~~~

### PR DESCRIPTION
**Pull request by scpeters**
Fixes #897.

### CODE REVIEW

**Comment by scpeters** [comment]
deferring to #900
