### PR TITLE
Fix experimental build regression: AVBD rigid contact vs compound CollisionGeometry

### PR DESCRIPTION
**Pull request by jslee02**
## Urgent: main does not currently compile

`main` fails to build the experimental simulation tests (`dart_experimental_tests`) due to a **semantic conflict between two separately-merged PRs**:

- **#2838** (PLAN-080 model loader) changed `comps::CollisionGeometry` from a single `shape` member to a `std::vector<CollisionShape> shapes` (compound-shape support), exposing `hasShapes()` / `getPrimaryShape()`.
- **#2837** (AVBD rigid contact feature keys) still reads `geometry->shape.{type,halfExtents,radius}` in `detail/deformable_vbd/rigid_world_contact.hpp`.

Both merged cleanly in git (no textual conflict) but are mutually inconsistent, so the tree no longer compiles:

```
rigid_world_contact.hpp:285: error: 'const struct ...comps::CollisionGeometry'
  has no member named 'shape'; did you mean 'shapes'?
```

This is a classic parallel-development *semantic* merge collision that the per-file git merge can't catch.

## Fix

Use `CollisionGeometry::getPrimaryShape()` (the first shape, matching the prior single-shape behavior) in the AVBD rigid-world contact feature-keying function, and skip endpoints whose geometry has no shape. Behavior-preserving for the existing single-shape bodies; for compound geometry it keys on the primary shape (box/cylinder/capsule indices remain 0, as before).

## Verification

- `pixi run build-simulation-experimental-tests` ✅ (was failing on `main`)
- `ctest -L simulation-experimental` → **58/58 pass**
- `pixi run lint` ✅

## Note

Recommend fast-tracking: until this lands, every PR's experimental build/CI is red. Found while rebasing other DART 7 work onto latest `main`.

### CODE REVIEW

**Comment by jslee02** [comment]
Redundant: the same fix (use `CollisionGeometry::getPrimaryShape()` in the AVBD rigid-contact feature keying) already landed on `main` via #2836 (commit b5922f4ddec). `main` now compiles the experimental tests; closing this duplicate.
